### ISSUE TITLE
请问是怎样解决快速按键焦点丢失的

### ISSUE THREAD

**Issue by zeroztguo** [lph2012/TvRecyclerView#1]
看源码看不太出来，困惑很久了

**Comment by littleloulou** [comment]
你是指当recyclerView快速滑动之后,焦点框错位吗？可以在recyclerView添加滑动监听,当滑动停止的时候获取当前得到焦点的itemView,然后设置选中效果.

**Comment by zeroztguo** [comment]
@zeroztguo 这个问题你要是解决了，麻烦分享一下解决办法啊

**Comment by littleloulou** [comment]
我的这个好像也有类似的问题,快速向下滑动的时候,焦点会跑到中间那一列

**Comment by littleloulou** [comment]
你可以尝试重写下RecyclerView的这个方法试试public View focusSearch(View focused, int direction),你说的情况应该是recyclerView在寻找获取焦点的view的时候，出现了问题,应该和它的策略有关系
